/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"Stm32F103C8T6.h"
#include"Clock_stm32.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(unsigned long int time);
int main(void)
{


	HSE_PLL_Clock(HSE,8,8);
	AHB_PR_DIV(0);
	APB1_PR_DIV(2);
	APB2_PR_DIV(2);
	GPIO_Clock(GPIOA);
	GPIO_Clock(GPIOB);
	GPIO_Clock(GPIOC);
	GPIO_input_output(GPIOA,0,Output);
	GPIO_input_output(GPIOB,1,Output);
	GPIO_input_output(GPIOC,13,Output);



    /* Loop forever */
	for(;;){

		GPIOA_ODR |=(1<<0);
		delay_ms(1000);
		GPIOA_ODR &=~(1<<0);
		delay_ms(1000);





	}
}




